### ISSUE TITLE
Typo in pretrained model name

### ISSUE THREAD

**Issue by NickShargan** [SimonGiebenhain/MonoNPHM#14]
There is a mismatch between checkpoint directory name and one that is used in README.md.

E.g. the command is:
```
python scripts/inference/rec.py --model_type nphm --exp_name pretrained_mononphm 
```

But checkpoint name is different:

![gdrive](https://github.com/user-attachments/assets/de3b0367-7b1b-4052-857b-50d1b66de36b)

**Comment by SimonGiebenhain** [comment]
Thanks, it is fixed now.
I also uploaded the model checkpoint that was used in the paper, called `pretrained_mononphm_original`. The hyperparameters for the tracking seem to be delicate and more suitable for that pretrained model.
