### ISSUE TITLE
Some loss are nan during fitting

### ISSUE THREAD

**Issue by weimengting** [SimonGiebenhain/MonoNPHM#16]
Hi,

I fit the model with my own images and preprocess them with the pipeline provided. However, there're some losses suddenly turn into NAN values in the fitting stage, as demonstrated in this picture:

![image](https://github.com/user-attachments/assets/6bf47a7f-8817-454e-879b-de449a3a78f2)

**Comment by SimonGiebenhain** [comment]
Hi, 
i haven't encounterd NaNs myself. 
Have you checked if the preprocessing looks reasonable? E.g. there can be problems if people are seen in the background.

There is also a variable called `progress_interval` in the [reconstruction code](https://github.com/SimonGiebenhain/MonoNPHM/blob/main/src/mononphm/photometric_tracking/tracking.py)
Currently it is set to such a high value that intermediate renderings are never performed. 
You can set it to, e.g. 50, which renders rgb reconstruction, color and solhouette losses every 50 optimization steps. Hopefully, this will helop to figure out what is causing the problem.
