### ISSUE TITLE
Problem of the reconstruction result

### ISSUE THREAD

**Issue by weimengting** [SimonGiebenhain/MonoNPHM#20]
Hi,

I tried the script of rec.py with the provided image ID=00995, but the result of mesh.ply seems very different from the input source image:

![00000](https://github.com/user-attachments/assets/116e5507-91ef-4ddb-a163-89077ff9741f)
![image](https://github.com/user-attachments/assets/1e728659-17f6-4bf4-908c-b3cdd446df8c)
Could you have ideas of how this happen?

**Comment by SimonGiebenhain** [comment]
Hey, 

which command did you run exactly?


When I run
`python scripts/inference/rec.py --model_type nphm --exp_name pretained_monnphm --ckpt 2500 --seq_name 00995 --no-intrinsics_provided --downsample_factor 0.33 --no-is_video 
`

I get the following result:

<img width="292" alt="Bildschirmfoto 2024-10-10 um 22 15 30" src="https://github.com/user-attachments/assets/68d128c7-942d-418c-8b38-78af5b65503c">
<img width="337" alt="Bildschirmfoto 2024-10-10 um 22 15 20" src="https://github.com/user-attachments/assets/c19db52e-61f4-4578-9d53-07e23006bb7e">

**Comment by Zvyozdo4ka** [comment]
Hello, @SimonGiebenhain 

I ran the same commands as you recommended, but my meshes does not resemble identities. Any recommendations how to improve? How downsample_factor affects the output mesh?

Input images:

![image](https://github.com/user-attachments/assets/78f9f898-a5e2-4fcf-8125-4b438227ee1b)

outputs:

![image](https://github.com/user-attachments/assets/a4aae580-b605-4542-b50c-0297439b5b90)

**Comment by weimengting** [comment]
> Hey,
> 
> which command did you run exactly?
> 
> When I run `python scripts/inference/rec.py --model_type nphm --exp_name pretained_monnphm --ckpt 2500 --seq_name 00995 --no-intrinsics_provided --downsample_factor 0.33 --no-is_video `
> 
> I get the following result:
> 
> <img alt="Bildschirmfoto 2024-10-10 um 22 15 30" width="292" src="https://private-user-images.githubusercontent.com/28050396/375533084-68d128c7-942d-418c-8b38-78af5b65503c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NjkyODAsIm5iZiI6MTcyODY2ODk4MCwicGF0aCI6Ii8yODA1MDM5Ni8zNzU1MzMwODQtNjhkMTI4YzctOTQyZC00MThjLThiMzgtNzhhZjViNjU1MDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDE3NDk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OWRhYjRiMDE5OWVkMzZlMGExMzI3NGRhMTY4ZTJkYTkxMzZhMmY2YjY0ODE2YjkxZTBkODE3MjU0MGEwZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9UuAGVAOClWgbQgof9WqOXnYRtn6T1Hm_9yWXujNZ5k"> <img alt="Bildschirmfoto 2024-10-10 um 22 15 20" width="337" src="https://private-user-images.githubusercontent.com/28050396/375533093-c19db52e-61f4-4578-9d53-07e23006bb7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NjkyODAsIm5iZiI6MTcyODY2ODk4MCwicGF0aCI6Ii8yODA1MDM5Ni8zNzU1MzMwOTMtYzE5ZGI1MmUtNjFmNC00NTc4LTlkNTMtMDdlMjMwMDZiYjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDE3NDk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZGFhMzIzODI2NTdjOGEzMmI5M2I1ODBhYWJmMjJmNWU3MTQ1MjBkMmFkNTI3YjJiMzc0YTRkNWMyNTc5YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZRETM21nFWfXrR09ce1XNUbWkUsRHD3IjZEXDf7eMlg">

Hi,

Thanks so much for the prompt reply! I tried with other computer and then all the problems are gone, which is very weird. I guess maybe the environment settings have problem on my local PC.
