### ISSUE TITLE
Running Inference Script: Epochs?

### ISSUE THREAD

**Issue by dondongwon** [SimonGiebenhain/MonoNPHM#23]
<img width="566" alt="image" src="https://github.com/user-attachments/assets/7ea4b968-0e02-4556-afe8-f5d96eb6cfa8">

Hi, thank you for this really exciting work! Was wondering why I'm getting loss metrics and epochs when I simply try to run the inference script from the demo. Here is the exact script I am using:

`python scripts/inference/rec.py --model_type nphm --exp_name pretrained_mononphm --ckpt 2500 --seq_name 00059 --no-intrinsics_provided --downsample_factor 0.33 --no-is_video`

**Comment by SimonGiebenhain** [comment]
That is just bad naming on my side. Instead of `Epoch` I should have used `Step`.
The losses are just the different energy terms which are minimized
