### ISSUE TITLE
Reconstruction from custom data failed

### ISSUE THREAD

**Issue by yuhongyun777** [SimonGiebenhain/MonoNPHM#3]
Thank you for your efforts! While running your code with the demo data, everything works perfectly; the mesh reconstruction aligns well with the expressions and shape of the demo data.

However, when I attempt to use my own data following your preprocessing steps, the reconstructed results seem very odd and inaccurate. I have reviewed the visualizations from the metrical-tracker and found no apparent issues. The segmentation and keypoint detection results also appear normal.

The only potential issue seems to be with the intrinsic and extrinsic parameters obtained from the metrical-tracker. Specifically, the focal length in the intrinsic parameters is significantly larger compared to the demo data, and the translation values in the extrinsic parameters are much smaller.

Could you please advise on what might be causing this problem?

Additionally, I utilized your preprocessing code to preprocess the demo data (00059) again. However, the reconstruction results are incorrect, similar to the issues I faced with my custom data. Therefore, I suspect the problem might lie within the preprocessing code or my environment setup. Could you provide some guidance on this matter?

reconstruction from demo_data 00059:
<img width="551" alt="image" src="https://github.com/SimonGiebenhain/MonoNPHM/assets/46377447/3e5d2a7c-4b07-4f4a-a21f-035df0f8f8b6">

reconstruction from my own data:
<img width="781" alt="image" src="https://github.com/SimonGiebenhain/MonoNPHM/assets/46377447/31f7736d-09e6-45c8-b657-7935787e1340">

metrical tracker results from my own data：
![image](https://github.com/SimonGiebenhain/MonoNPHM/assets/46377447/1cbee4d4-298b-44be-b8c2-1e1e9d38d8e2)

intrinsic and extrinsic diff：
<img width="1458" alt="3A7B156B-F612-4DB7-B6F6-4E98AC033094" src="https://github.com/SimonGiebenhain/MonoNPHM/assets/46377447/3ab10c5a-a1a0-45c1-996d-191ad8fdc9d2">

**Comment by SimonGiebenhain** [comment]
Hi,
Is it possible that you ran `bash run.sh SEQ_NAME --intrinsics_provided `?

The `—intrinsics_provided` flag will ignore the estimated intrinsics from MICA and use the intrinsics from our test camera instead.



If that is the case, can you try again with `—no-intrinsics_provided`?

**Comment by Zvyozdo4ka** [comment]
@yuhongyun777 what is your cuda version?

**Comment by Megidd** [comment]
@Zvyozdo4ka My CUDA information:

```bash
nvidia-smi

Wed Sep 11 12:44:11 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060        Off |   00000000:41:00.0 Off |                  N/A |
|  0%   40C    P8             14W /  170W |      13MiB /  12288MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1382      G   /usr/lib/xorg/Xorg                              6MiB |
+-----------------------------------------------------------------------------------------+
```


# Custom image

How I ran for a custom image on a CUDA server:

### Input

```bash
scp Documents/MonoNPHM\ input/00020/source/00000.png arisa@IP.IP.IP.IP:/home/arisa/MONONPHM_DATA_TRACKING/00020/source/
```

### Preprocess

```bash
cd /home/arisa/MonoNPHM
conda activate mononphm
cd scripts/preprocessing/
bash run.sh 00020 --no-intrinsics_provided
```

### Run

```bash
/home/arisa/MonoNPHM
conda activate mononphm
python3.9 scripts/inference/rec.py --model_type nphm --exp_name pretrained_mononphm --ckpt 2500 --seq_name 00020 --no-intrinsics_provided --downsample_factor 0.33
```

### Output

```bash
 scp arisa@IP.IP.IP.IP:/home/arisa/MONONPHM_TRACKING_OUTPUT/pretrained_mononphm/stage1/00020/00000/mesh.ply Downloads/
```

# Result

![2024-09-11 01_57_29](https://github.com/user-attachments/assets/1bc6e2ad-9f5b-4b61-b423-8b52fc3d676b)
![2024-09-11 01_59_18](https://github.com/user-attachments/assets/dadb1ec4-e830-4aac-832c-7c0212484d61)
![2024-09-11 02_00_10](https://github.com/user-attachments/assets/d3332e55-a4f2-4228-ad6e-ca6bd4a0c04c)
![2024-09-11 02_00_31](https://github.com/user-attachments/assets/b5cbbd22-0632-4745-9a8e-72a02a55db31)

# Troubleshooting

* Apparently, MonoNPHM expects the input image to have the same *width* and *height*.
   * Otherwise, the `run_metrical_tracker.py` script would throw errors.
* Apparently, MonoNPHM cannot detect face boxes for _some_ custom images. It happens at times 😣 
   * However, it doesn't throw well-informed errors/warnings.
* Apparently, MonoNPHM expects the input custom image to be a PNG with RGB without the alpha channel.
   * Take a look at this PR: https://github.com/SimonGiebenhain/MonoNPHM/pull/11
* Make sure you have installed Numpy version `1.23` and *not* a newer version.
   * Otherwise, you will get errors.
* While running commands, make sure the Conda env is activated by `conda activate mononphm`
   * Make sure the Python packages are actually used from the Conda env and *not* the system.
   * Conda on my server sometimes uses system packages even though I have activated the env.
* Sometimes the Pytorch script has problems downloading files like `face_parsing.farl.celebm.main_ema_181500_jit.pt`
   * In that case, download them manually and transfer them to `~/.cache/torch/hub/checkpoints/` location on your server.

**Comment by Megidd** [comment]
@Zvyozdo4ka I guess my installed CUDA versions are these:

```bash
whereis -b cuda
cuda: /usr/local/cuda
```

```bash
cat /usr/local/cuda/version.json | less
```

<details><summary>Expand `version.json` file content</summary>

```json
{
   "cuda" : {
      "name" : "CUDA SDK",
      "version" : "12.3.1"
   },
   "cuda_cccl" : {
      "name" : "CUDA C++ Core Compute Libraries",
      "version" : "12.3.101"
   },
   "cuda_cudart" : {
      "name" : "CUDA Runtime (cudart)",
      "version" : "12.3.101"
   },
   "cuda_cuobjdump" : {
      "name" : "cuobjdump",
      "version" : "12.3.101"
   },
   "cuda_cupti" : {
      "name" : "CUPTI",
      "version" : "12.3.101"
   },
   "cuda_cuxxfilt" : {
      "name" : "CUDA cu++ filt",
      "version" : "12.3.101"
   },
   "cuda_demo_suite" : {
      "name" : "CUDA Demo Suite",
      "version" : "12.3.101"
   },
   "cuda_gdb" : {
      "name" : "CUDA GDB",
      "version" : "12.3.101"
   },
   "cuda_nsight" : {
      "name" : "Nsight Eclipse Plugins",
      "version" : "12.3.101"
   },
   "cuda_nvcc" : {
      "name" : "CUDA NVCC",
      "version" : "12.3.103"
   },
   "cuda_nvdisasm" : {
      "name" : "CUDA nvdisasm",
      "version" : "12.3.101"
   },
   "cuda_nvml_dev" : {
      "name" : "CUDA NVML Headers",
      "version" : "12.3.101"
   },
   "cuda_nvprof" : {
      "name" : "CUDA nvprof",
      "version" : "12.3.101"
   },
   "cuda_nvprune" : {
      "name" : "CUDA nvprune",
      "version" : "12.3.101"
   },
   "cuda_nvrtc" : {
      "name" : "CUDA NVRTC",
      "version" : "12.3.103"
   },
   "cuda_nvtx" : {
      "name" : "CUDA NVTX",
      "version" : "12.3.101"
   },
   "cuda_nvvp" : {
      "name" : "CUDA NVVP",
      "version" : "12.3.101"
   },
   "cuda_opencl" : {
      "name" : "CUDA OpenCL",
      "version" : "12.3.101"
   },
   "cuda_sanitizer_api" : {
      "name" : "CUDA Compute Sanitizer API",
      "version" : "12.3.101"
   },
   "fabricmanager" : {
      "name" : "Fabric Manager",
      "version" : "545.23.08"
   },
   "libcublas" : {
      "name" : "CUDA cuBLAS",
      "version" : "12.3.4.1"
   },
   "libcufft" : {
      "name" : "CUDA cuFFT",
      "version" : "11.0.12.1"
   },
   "libcufile" : {
      "name" : "GPUDirect Storage (cufile)",
      "version" : "1.8.1.2"
   },
   "libcurand" : {
      "name" : "CUDA cuRAND",
      "version" : "10.3.4.101"
   },
   "libcusolver" : {
      "name" : "CUDA cuSOLVER",
      "version" : "11.5.4.101"
   },
   "libcusparse" : {
      "name" : "CUDA cuSPARSE",
      "version" : "12.2.0.103"
   },
   "libnpp" : {
      "name" : "CUDA NPP",
      "version" : "12.2.3.2"
   },
   "libnvidia_nscq" : {
      "name" : "NvSwitch Library",
      "version" : "545.23.08"
   },
   "libnvjitlink" : {
      "name" : "JIT Linker Library",
      "version" : "12.3.101"
   },
   "libnvjpeg" : {
      "name" : "CUDA nvJPEG",
      "version" : "12.3.0.81"
   },
   "nsight_compute" : {
      "name" : "Nsight Compute",
      "version" : "2023.3.1.1"
   },
   "nsight_systems" : {
      "name" : "Nsight Systems",
      "version" : "2023.3.3.42"
   },
   "nvidia_driver" : {
      "name" : "NVIDIA Linux Driver",
      "version" : "545.23.08"
   },
   "nvidia_fs" : {
      "name" : "NVIDIA file-system",
      "version" : "2.18.3"
   }
}
```

</details>

**Comment by Zvyozdo4ka** [comment]
@Megidd hello. Thank you for detailed response, i appreciate it. May i see the image of the person you are referring to as an output mesh?

**Comment by Megidd** [comment]
@Zvyozdo4ka Sure. Here is one of the custom images run through MonoNPHM:

# Custom image

## Width == height

I have increased the width of the image by extra pixels to make the width be equal to height. Apparently equality of width and height is required by MonoNPHM.

![00000](https://github.com/user-attachments/assets/c605b7df-ec4d-4465-ae7b-601db706a5c7)

# Result

![2024-09-16 00_35_30-MeshLab 2022 02 -  Project_1](https://github.com/user-attachments/assets/52aeecfc-a6c3-4094-8a3d-0954bb5c3454)

![2024-09-16 00_35_45-MeshLab 2022 02 -  Project_1](https://github.com/user-attachments/assets/447e837c-0c31-4eed-92c4-a2e66e0b2b38)

![2024-09-16 00_36_06-MeshLab 2022 02 -  Project_1](https://github.com/user-attachments/assets/ab759f71-d834-4315-ba76-7c5a0d36e801)

![2024-09-16 00_36_26-MeshLab 2022 02 -  Project_1](https://github.com/user-attachments/assets/3c29862e-dd1e-4584-85b6-0e25568a3784)

**Comment by Zvyozdo4ka** [comment]
@Megidd I appreciate your detailed explanation. Thank you. I finally got managed to change drivers, installed cuda 11.7 and set environment. 
 
But my experiments do not resemble the identity at all, to the contrary to your results. How did you get such a good output?

I followed your instructions regarding requirements to image, and I put it to source folder. 
Then I ran these commands:

1. ``` bash run.sh 00103 --intrinsics_provided```

2. ```python3.9 scripts/inference/rec.py --model_type nphm --exp_name pretrained_mononphm --ckpt 2500 --seq_name 00020  --intrinsics_provided ```

Experiment 1. 
![00000](https://github.com/user-attachments/assets/18273154-1728-4f4d-8dc8-44955556f23c)

![image](https://github.com/user-attachments/assets/ed362b87-308e-44fb-b7c6-252605544445)

Experiment 2.
![00000](https://github.com/user-attachments/assets/4c843681-06c0-43d1-94f1-c3633dfbe0b1)


![image](https://github.com/user-attachments/assets/272e2c66-fd12-42da-8baf-3d39d6393913)




Do you know why it is impossible to run other demo experiments? Only 00995 worked, I always have  this issue:
```
Traceback (most recent call last):
  File "/media/yulduz/hdd/Projects/MonoNPHM/scripts/inference/rec.py", line 194, in <module>
    tyro.cli(main)
  File "/home/yulduz/anaconda3/envs/mononphm/lib/python3.9/site-packages/tyro/_cli.py", line 229, in cli
    return run_with_args_from_cli()
  File "/media/yulduz/hdd/Projects/MonoNPHM/scripts/inference/rec.py", line 185, in main
    inverse_rendering(n3dmm, seq_name, _expressions, n_expr,
  File "/media/yulduz/hdd/Projects/MonoNPHM/scripts/inference/rec.py", line 59, in inverse_rendering
    track(wrapped_net, cfg, seq_name, expressions,
  File "/media/yulduz/hdd/Projects/MonoNPHM/src/mononphm/photometric_tracking/tracking.py", line 1409, in track
    tracker.rec_and_save( progress_interval)
  File "/media/yulduz/hdd/Projects/MonoNPHM/src/mononphm/photometric_tracking/tracking.py", line 1205, in rec_and_save
    vertex_color = get_vertex_color(self.idr.implicit_network.monoNPHM,
  File "/media/yulduz/hdd/Projects/MonoNPHM/src/mononphm/models/reconstruction.py", line 133, in get_vertex_color
    color = torch.cat(color_list, dim=0).numpy()
RuntimeError: torch.cat(): expected a non-empty list of Tensors
```

**Comment by Zvyozdo4ka** [comment]
Hello, @SimonGiebenhain 

Could you give a hint how to improve the resemblance of the person? What if to train from scratch which includes many Asian faces?

**Comment by Zvyozdo4ka** [comment]
> Additionally, I utilized your preprocessing code to preprocess the demo data (00059) again. However, the reconstruction results are incorrect, similar to the issues I faced with my custom data. Therefore, I suspect the problem might lie within the preprocessing code or my environment setup. Could you provide some guidance on this matter?

> reconstruction from my own data: <img alt="image" width="781" src="https://private-user-images.githubusercontent.com/46377447/342272737-31f7736d-09e6-45c8-b657-7935787e1340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MTI0MTAsIm5iZiI6MTcyNzQxMjExMCwicGF0aCI6Ii80NjM3NzQ0Ny8zNDIyNzI3MzctMzFmNzczNmQtMDllNi00NWM4LWI2NTctNzkzNTc4N2UxMzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA0NDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3OTUxYTBjZTVmMzQ1MTgxNzI0NDcwMmJjNTIyNjMzZTRhYWQwM2VmOTU2OGZlMDUwMzRjOWM3MjJiYWI0MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iz3Q_f74faxKgCjBJcWD2mX9T9dVQsB6PrJF7CErhxA">
> 
Hello, @yuhongyun777 

Did you manage to resolve this issue?

**Comment by Megidd** [comment]
> But my experiments do not resemble the identity at all, to the contrary to your results. How did you get such a good output?

@Zvyozdo4ka I have also run into some not-so-perfect results. Mostly for _children_ and some minority demographics.

However, MonoNPHM is:

* Extremely reliable, robust, well-organized.
* Extensible by training through new data sets.
   * New data sets should contain _children_.
   * New data sets should contain a wide demography of people.

**Comment by Megidd** [comment]
@Zvyozdo4ka I feel like you made a mistake about an option. You must use this option: `--no-intrinsics_provided` ✔️ 

Please refer to my previous comments for details.

**Comment by Megidd** [comment]
> Did you manage to train with new datasets? I think Asian type of face should be added

@Zvyozdo4ka No, I didn't train yet. Actually, I'm _not_ quite sure how to do it.

Do I have to get the MonoNPHM Test Data? I believe I submitted a form to get their _test_ data. But I didn't hear back from them.

![2024-09-30 01_44_20-SimonGiebenhain_MonoNPHM_  CVPR 2024 Highlight  - Opera](https://github.com/user-attachments/assets/67b4d3e0-57d9-4ca4-97a3-e3bbb7b670ca)

**Comment by Zvyozdo4ka** [comment]
> > Did you manage to train with new datasets? I think Asian type of face should be added
> 
> @Zvyozdo4ka No, I didn't train yet. Actually, I'm _not_ quite sure how to do it.
> 
> Do I have to get the MonoNPHM Test Data? I believe I submitted a form to get their _test_ data. But I didn't hear back from them.
> 
> ![2024-09-30 01_44_20-SimonGiebenhain_MonoNPHM_ CVPR 2024 Highlight - Opera](https://private-user-images.githubusercontent.com/17475482/372012700-67b4d3e0-57d9-4ca4-97a3-e3bbb7b670ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MzMxNDksIm5iZiI6MTcyNzgzMjg0OSwicGF0aCI6Ii8xNzQ3NTQ4Mi8zNzIwMTI3MDAtNjdiNGQzZTAtNTdkOS00Y2E0LTk3YTMtZTNiYmI3YjY3MGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDAxMzQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZDkyMzYyM2NjNTdlMTg3ZmY1M2JlOGRiYTc4ZTQ0MTYyYTA5NTkxNGM0MjdiYzFlOTAyNjYzYjFiMjEyZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KkD2yojecQnqcul0xx4nxEjTeSTDg2Fz5IN4u1p76HM)

@Megidd I do not know how to perform training either.
Yes, I think we need Test Data, and Training Data, and we need to know how to normalize training data. I hope @SimonGiebenhain can give us some guidance on that.
