### ISSUE TITLE
Problem with paths

### ISSUE THREAD

**Issue by Zvyozdo4ka** [SimonGiebenhain/MonoNPHM#7]
what is expected to be in DATA_TRACKING2 path?

I have this error, but i did not find description about this path.
```
    new_mica_pose = np.load(f'{env_paths.DATA_TRACKING2}/s{seq_name[6:]}/checkpoint/{max(timestep - 1, 0):05d}_cam_params_opencv.npz')
AttributeError: module 'mononphm.env_paths' has no attribute 'DATA_TRACKING2'
```

**Comment by SimonGiebenhain** [comment]
Hi, 

it seems that I forgot to remove the `try`-`except`-statement. 
It is never supposed to fail there. It seems that you ran the code without `--no-intrinsics_provided`. 
In that case it attempts to read the camera intrinsics here, which are missing in your case.

**Comment by Zvyozdo4ka** [comment]
Hello!

> it seems that I forgot to remove the `try`-`except`-statement. It is never supposed to fail there. 

Thank you!

> It seems that you ran the code without `--no-intrinsics_provided`. In that case it attempts to read the camera intrinsics here, which are missing in your case.

I tried with `--no-intrinsics_provided`, and now it turned out that i have problem with CUDA. Do you know how to resolve it?

```
python scripts/inference/rec.py --model_type nphm --exp_name pretrained_mononphm --ckpt 2500 --seq_name 00898 --no-intrinsics_provided --downsample_factor 0.33

FOUND 1 GPUs
/home/yulduz/anaconda3/envs/mononphm-8/lib/python3.9/site-packages/torch/cuda/__init__.py:146: UserWarning: 
NVIDIA GeForce RTX 3080 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  ANCHORS HAVE SHAPE:  torch.Size([1, 1, 65, 3])
creating DeepSDF with...
lat dim 116
hidden_dim 400
3_Creating DeepSDF with input dim f119, hidden_dim f400 and output_dim 5
/home/yulduz/anaconda3/envs/mononphm-8/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/yulduz/anaconda3/envs/mononphm-8/lib/python3.9/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
USING EPOCH MULT OF: 1

Traceback (most recent call last):
  File "/MonoNPHM/scripts/inference/rec.py", line 194, in <module>
    tyro.cli(main)
  File "/home/yulduz/anaconda3/envs/mononphm-8/lib/python3.9/site-packages/tyro/_cli.py", line 217, in cli
    return run_with_args_from_cli()
  File "/MonoNPHM/scripts/inference/rec.py", line 185, in main
    inverse_rendering(n3dmm, seq_name, _expressions, n_expr,
  File "/MonoNPHM/scripts/inference/rec.py", line 59, in inverse_rendering
    track(wrapped_net, cfg, seq_name, expressions,
  File "/MonoNPHM/src/mononphm/photometric_tracking/tracking.py", line 1366, in track
    loss_backwarp = tracker.compute_landmark_loss(loss_dict, epoch, epoch_mult, current_expression, rnd_idx, can_anchors, data_manager)
  File "/MonoNPHM/src/mononphm/photometric_tracking/tracking.py", line 855, in compute_landmark_loss
    p_corresp_posed, search_result = search(can_anchors,
  File "/MonoNPHM/src/mononphm/models/iterative_root_finding.py", line 127, in search

    J_inv_init = jac(decoder_expr, in_dict).inverse()
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by self-hacker** [comment]
I met this issue too,my solution is changing the "FFHQ_ID" in "python scripts/inference/rec.py --model_type nphm --exp_name pretrained_mononphm --ckpt 2500 --seq_name FFHQ_ID --no-intrinsics_provided --downsample_factor 0.33" with the real ID like "00995" so that you can make the "try..." sentence in data_loading.py run successfully.

**Comment by Zvyozdo4ka** [comment]
> Hi,
> 
> it seems that I forgot to remove the `try`-`except`-statement. It is never supposed to fail there. It seems that you ran the code without `--no-intrinsics_provided`. In that case it attempts to read the camera intrinsics here, which are missing in your case.

Hello, @SimonGiebenhain.

If to run with --no-intrinsics provided, it throws errors:

```Traceback (most recent call last):
  File "/media/yulduz/hdd/Projects/MonoNPHM/src/mononphm/photometric_tracking/data_loading.py", line 89, in prepare_data
    facer_mask = Image.open(f'{env_paths.DATA_TRACKING}/{seq_name}/seg/{timestep}.png')
  File "/home/yulduz/anaconda3/envs/mononphm/lib/python3.9/site-packages/PIL/Image.py", line 3227, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/media/yulduz/hdd/Projects/MonoNPHM/mononphm_paths/input/00020/seg/1.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/yulduz/hdd/Projects/MonoNPHM/scripts/inference/rec.py", line 194, in <module>
    tyro.cli(main)
  File "/home/yulduz/anaconda3/envs/mononphm/lib/python3.9/site-packages/tyro/_cli.py", line 229, in cli
    return run_with_args_from_cli()
  File "/media/yulduz/hdd/Projects/MonoNPHM/scripts/inference/rec.py", line 185, in main
    inverse_rendering(n3dmm, seq_name, _expressions, n_expr,
  File "/media/yulduz/hdd/Projects/MonoNPHM/scripts/inference/rec.py", line 59, in inverse_rendering
    track(wrapped_net, cfg, seq_name, expressions,
  File "/media/yulduz/hdd/Projects/MonoNPHM/src/mononphm/photometric_tracking/tracking.py", line 1282, in track
    data_manager = SimpleDataManager(expressions, seq_name, cfg,
  File "/media/yulduz/hdd/Projects/MonoNPHM/src/mononphm/photometric_tracking/tracking.py", line 320, in __init__
    res_cleaned = prepare_data(timestep=expression, seq_name=seq_name,
  File "/media/yulduz/hdd/Projects/MonoNPHM/src/mononphm/photometric_tracking/data_loading.py", line 91, in prepare_data
    rgb = Image.open(f'{env_paths.KINECT_DATA}/{seq_name}/color/{timestep:05d}.png')
AttributeError: module 'mononphm.env_paths' has no attribute 'KINECT_DATA'
```

**Comment by SimonGiebenhain** [comment]
Hello @Zvyozdo4ka have you followed the instructions [here](https://github.com/SimonGiebenhain/MonoNPHM?tab=readme-ov-file#12-environment-paths) ?
Also, have you performed the preprocessing for `FFHQ_ID=00020` ? If not you can start with the IDs in the provided [demo data](https://drive.google.com/drive/folders/1XHHabTt_IgYPmGZj0Gj1dyTm7dwyGEvb?usp=drive_link).

**Comment by SimonGiebenhain** [comment]
> I met this issue too,my solution is changing the "FFHQ_ID" in "python scripts/inference/rec.py --model_type nphm --exp_name pretrained_mononphm --ckpt 2500 --seq_name FFHQ_ID --no-intrinsics_provided --downsample_factor 0.33" with the real ID like "00995" so that you can make the "try..." sentence in data_loading.py run successfully.

Actually, I forgot to append the `--no-is_video` flag in the instructions. You can try again with this flag, which tends to give nicer results.

**Comment by Zvyozdo4ka** [comment]
> > I met this issue too,my solution is changing the "FFHQ_ID" in "python scripts/inference/rec.py --model_type nphm --exp_name pretrained_mononphm --ckpt 2500 --seq_name FFHQ_ID --no-intrinsics_provided --downsample_factor 0.33" with the real ID like "00995" so that you can make the "try..." sentence in data_loading.py run successfully.
> 
> Actually, I forgot to append the `--no-is_video` flag in the instructions. You can try again with this flag, which tends to give nicer results.

I prepared 9 images to test, followed instructions for image processing from @Megidd #3 
Created folder for each image named after image and copied image  as ```image_name/source/00000.png```, then ran this:

```
cd scripts/preprocessing

bash run.sh 00000 --no-intrinsics_provided --no-is_video

cd ../inference

python3 rec.py --model_type nphm --exp_name pretrained_mononphm --ckpt 2500 --seq_name 00000 --no-intrinsics_provided --no-is_video

python3 rec.py --model_type nphm --exp_name pretrained_mononphm --ckpt 2500 --seq_name 00000 --no-intrinsics_provided --is_stage2
```

Is it correct now? 

Input images:

![image](https://github.com/user-attachments/assets/78f9f898-a5e2-4fcf-8125-4b438227ee1b)

First 4 outputs:

![image](https://github.com/user-attachments/assets/d0875aa0-1e5d-4909-99cd-14ab6f240639)

**Comment by Zvyozdo4ka** [comment]
@SimonGiebenhain, what is  --downsample_factor 0.33? How would it affect  output? I did not find mentions about this parameter in paper or documentation

**Comment by Zvyozdo4ka** [comment]
@SimonGiebenhain  And may I ask if there is requirements to video file too?

**Comment by Megidd** [comment]
> I prepared 9 images to test, followed instructions for image processing from @Megidd #3 Created folder for each image named after image and copied image as `image_name/source/00000.png`, then ran this:
> 
> ```
> cd scripts/preprocessing
> 
> bash run.sh 00000 --no-intrinsics_provided --no-is_video
> 
> cd ../inference
> 
> python3 rec.py --model_type nphm --exp_name pretrained_mononphm --ckpt 2500 --seq_name 00000 --no-intrinsics_provided --no-is_video
> 
> python3 rec.py --model_type nphm --exp_name pretrained_mononphm --ckpt 2500 --seq_name 00000 --no-intrinsics_provided --is_stage2
> ```
> 

@Zvyozdo4ka I tried your approach to run multiple images at once. 

I tried different configurations to create a `--seq_name` of the `00026` batch consisting of 3 images.

1st configuration tried:

```bash
MONONPHM_DATA_TRACKING/00026/image_01/source/00000.png
MONONPHM_DATA_TRACKING/00026/image_02/source/00000.png
MONONPHM_DATA_TRACKING/00026/image_03/source/00000.png
```

2nd configuration tried:

```bash
MONONPHM_DATA_TRACKING/00026/source/image_01/source/00000.png
MONONPHM_DATA_TRACKING/00026/source/image_02/source/00000.png
MONONPHM_DATA_TRACKING/00026/source/image_03/source/00000.png
```

The following command threw errors for both 1st & 2nd tries indicating the expected configuration is different ⚠️ 

```bash
bash run.sh 00026 --no-intrinsics_provided --no-is_video
```

What is your exact configuration? Thanks.

**Comment by Zvyozdo4ka** [comment]
> @Zvyozdo4ka I tried your approach to run multiple images at once.
> 
> I tried different configurations to create a `--seq_name` of the `00026` batch consisting of 3 images.
> 
> 1st configuration tried:
> 
> ```shell
> MONONPHM_DATA_TRACKING/00026/image_01/source/00000.png
> MONONPHM_DATA_TRACKING/00026/image_02/source/00000.png
> MONONPHM_DATA_TRACKING/00026/image_03/source/00000.png
> ```
> 
> 2nd configuration tried:
> 
> ```shell
> MONONPHM_DATA_TRACKING/00026/source/image_01/source/00000.png
> MONONPHM_DATA_TRACKING/00026/source/image_02/source/00000.png
> MONONPHM_DATA_TRACKING/00026/source/image_03/source/00000.png
> ```
> 

> ```
> 
> What is your exact configuration? Thanks.

My configuration was: 

```shell
MONONPHM_DATA_TRACKING/00995/source/00000.png
MONONPHM_DATA_TRACKING/00995/source/00001.png
MONONPHM_DATA_TRACKING/00995/source/00002.png
```

**Comment by Megidd** [comment]
> My configuration was:
> 
> ```shell
> MONONPHM_DATA_TRACKING/00995/source/00000.png
> MONONPHM_DATA_TRACKING/00995/source/00001.png
> MONONPHM_DATA_TRACKING/00995/source/00002.png
> ```

@Zvyozdo4ka Thanks, I did the following steps based on your configuration and the errors are resolved. But I have one question about the outputs.

# Steps

The `00026` folder is prepared with the required structure:

```
MONONPHM_DATA_TRACKING/00026/source/00000.png
MONONPHM_DATA_TRACKING/00026/source/00001.png
MONONPHM_DATA_TRACKING/00026/source/00002.png
```

Preprocessed by:

```bash
cd ~/MonoNPHM/scripts/preprocessing/
bash run.sh 00026 --no-intrinsics_provided --no-is_video
```

Ran by:

```bash
cd ~/MonoNPHM/
python3.9 scripts/inference/rec.py --model_type nphm --exp_name pretrained_mononphm_original --ckpt 2500 --seq_name 00026 --no-intrinsics_provided --downsample_factor 0.33 --no-is_video
```

# Question ❓ 

However, I can see the `mesh.ply` output only created for the first image `00000` at:

```bash
MONONPHM_TRACKING_OUTPUT/pretrained_mononphm_original/stage1/00026/00000/mesh.ply
```

For some reason, I cannot find the output for 2nd `00001` and 3rd `00002` images. Am I missing something? 🙄

**Comment by Zvyozdo4ka** [comment]
@Megidd i had exactly the same output. I didn't understand why

**Comment by Megidd** [comment]
> @Megidd i had exactly the same output. I didn't understand why

@Zvyozdo4ka  Thanks for clarification. I was assuming that your attached output meshes resulted from the _batch_ run of multiple input images.

So, I'm going to continue running input images one by one. Not a big deal in my case.

**Comment by Zvyozdo4ka** [comment]
> > @Megidd i had exactly the same output. I didn't understand why
> 
> @Zvyozdo4ka Thanks for clarification. I was assuming that your attached output meshes resulted from the _batch_ run of multiple input images.
> 
> So, I'm going to continue running input images one by one. Not a big deal in my case.

I wrote a script to run  with one command in run_images.sh multiple images in folder 'images'.

I put all images into folder images, then by image name folder created, and in this folder source folder created, and put image with name 00000.png. I can find and share this script tomorrow

**Comment by Megidd** [comment]
> ... I can find and share this script tomorrow

@Zvyozdo4ka Thanks. That would be helpful.

**Comment by Zvyozdo4ka** [comment]
> > ... I can find and share this script tomorrow
> 
> @Zvyozdo4ka Thanks. That would be helpful.

put folder mononphm_processing to scripts folder and then just run `run_images.sh`

[copying_images_to_dataset.zip](https://github.com/user-attachments/files/17856974/copying_images_to_dataset.zip)

**Comment by Megidd** [comment]
> put folder mononphm_processing to scripts folder and then just run `run_images.sh`

@Zvyozdo4ka Thanks.

<details><summary>Expand scripts</summary>

`images_2_input.py` file:

```python
import os
import shutil
from pathlib import Path
import argparse

def organize_images(input_platform_folder: Path, input_mononphm: Path):
    # Create dataset/input folder if not exists
    dataset_input_mononphm_folder = input_mononphm
    dataset_input_mononphm_folder.mkdir(parents=True, exist_ok=True)
    
    # Get all image files from input_folder
    # image_extensions = ['*.jpg', '*.jpeg', '*.png', '*.JPG', '*.JPEG', '*.PNG']
    image_extensions = ['*.png']
    image_paths = []
    for ext in image_extensions:
        image_paths.extend(Path(input_platform_folder).glob(ext))

    if len(image_paths) == 0:
        raise FileNotFoundError(f"No images found in {input_platform_folder} with the specified formats.")
    
    # Process each image
    for image_path in image_paths:
        image_name = image_path.stem  # Get the image name without extension

        # Create folder structure dataset/input/image_name/source/
        target_folder = dataset_input_mononphm_folder / image_name / "source"
        target_folder.mkdir(parents=True, exist_ok=True)

        # Define the target file path as 00000.png
        target_image_path = target_folder / "00000.png"

        # Copy the original image to the target location as 00000.png
        shutil.copy(image_path, target_image_path)

        print(f"Copied {image_path} to {target_image_path} \n")

# Main block for argparse
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Organize images into dataset folder structure")
    parser.add_argument('--input_platform_folder', type=str, required=True, help="Path to the input folder containing images")
    parser.add_argument('--input_mononphm', type=str, required=True, help="Path to the output folder where dataset will be created")

    args = parser.parse_args()

    input_platform_folder = Path(args.input_platform_folder)
    input_mononphm = Path(args.input_mononphm)

    organize_images(input_platform_folder, input_mononphm)
```

`process_images_in_run.py` file:

```python

import subprocess
from pathlib import Path
import argparse
import shutil


# def process_images(input_platform_folder: Path, mononphm_folder: Path):
def process_images(input_platform_folder: Path, mononphm_folder: Path, output_folder: Path):
    image_paths = list(input_platform_folder.glob('*.png'))

    if not image_paths:
        raise FileNotFoundError(f"No PNG images found in {input_platform_folder}")

    for image_path in image_paths:
        name_of_image = image_path.stem
        
        preprocessing_folder = mononphm_folder / "scripts" / "preprocessing"
        inference_folder = mononphm_folder / "scripts" / "inference"

        # Check if preprocessing directory exists
        if not preprocessing_folder.is_dir():
            print(f"Preprocessing directory not found: {preprocessing_folder}")
            continue

        # Run preprocessing command
        preprocess_command = f"cd {preprocessing_folder} && bash run.sh {name_of_image} --no-intrinsics_provided --no-is_video"
        
        # Check if inference directory exists
        if not inference_folder.is_dir():
            print(f"Inference directory not found: {inference_folder}")
            continue
            
        # Run inference command
        inference_command = f"cd {inference_folder} && python3 rec.py --model_type nphm --exp_name pretrained_mononphm --ckpt 2500 --seq_name {name_of_image} --no-intrinsics_provided --no-is_video"

        try:
            subprocess.run(preprocess_command, shell=True, check=True)
            subprocess.run(inference_command, shell=True, check=True)
        except subprocess.CalledProcessError as e:
            print(f"An error occurred while processing {name_of_image}: {e}")
            continue  # Skip to the next image

        # Define the source and destination paths for the mesh file
        mesh_source = mononphm_folder / "dataset" / "output" / "pretrained_mononphm" / "stage1" / name_of_image / "00000" / "mesh.ply"
        # output_path = output_folder / name_of_image / "_mononphm.ply"
        output_path = output_folder / name_of_image / f"{name_of_image}_mononphm.ply"

        
        # Create the output directory if it doesn't exist
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Copy the mesh.ply file to the output directory
        try:
            shutil.copy(mesh_source, output_path)
            print(f"Copied mesh.ply to {output_path}")
        except FileNotFoundError:
            print(f"Mesh file not found for {name_of_image}: {mesh_source}")
        except Exception as e:
            print(f"An error occurred while copying the file: {e}")



if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Process images in the INPUT_platform_FOLDER")
    parser.add_argument('--input_folder', type=str, required=True, help="Path to the input platform folder containing images")
    parser.add_argument('--mononphm_folder', type=str, required=True, help="Path to the scripts folder")
    parser.add_argument('--output_folder', type=str, required=True, help="Path to the output folder where mesh.ply will be copied")

    args = parser.parse_args()

    input_platform_folder = Path(args.input_folder)
    mononphm_folder = Path(args.mononphm_folder)
    output_folder = Path(args.output_folder)

    process_images(input_platform_folder, mononphm_folder, output_folder)

    # process_images(input_platform_folder, mononphm_folder)
```

</details>

**Comment by Zvyozdo4ka** [comment]
@Megidd Could you share you outputs? i wonder if they resemble identity

**Comment by Megidd** [comment]
@Zvyozdo4ka Sure. This is a sample result.

![00000](https://github.com/user-attachments/assets/fb02449b-60ba-4808-bc96-4cf024c36575)

![2024-11-21 01_16_22-MeshLab 2022 02 -  Project_1](https://github.com/user-attachments/assets/cf4fd066-a5cf-4eeb-92ca-5f2a092bb889)

**Comment by Zvyozdo4ka** [comment]
@Megidd  Thank you! I wonder why your outputs are always better in identity resemblance.
Is it your original input image? With what command did you run this?
